### ISSUE TITLE
Предложение по понижению связанности

### ISSUE THREAD

**Issue by misterx** [kruglikdenis/symfony-skeleton#1]
Как я вижу используется [src/Core/Http/BaseAction.php](../blob/master/src/Core/Http/BaseAction.php) суто для того что бы flush делать. Можно сделать отдельный класс Flush
```php
<?php

namespace App\Core\Http;


use Doctrine\ORM\EntityManagerInterface;

class Flush
{
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    public function __invoke():void
    {
        $this->em->flush();
    }

}
```

И инджектить его в action. Таким образом избавится от обязательного наследования.

Например

```php
public function __invoke(CreateRequest $request, Service $service, Flush $flush)
    {
       $service->someCreate($request);
       $flush();
    }
```

**Comment by kruglikdenis** [comment]
Мне кажется это отличное предложение.

Спасибо.

**Comment by kruglikdenis** [comment]
Внес изменения 

[commit](https://github.com/kruglikdenis/symfony-skeleton/commit/567be52998b96f2aa9b9fe25dd8fbb7b386c4eac)
